name: Release Chirp Executable

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux-x64, win-x64, osx-x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 7.x SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore .NET dependencies
      run: dotnet restore

    - name: Build .NET application
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal

    - name: Publish for each platform
      run: dotnet publish ./src/Chirp.CLI.Client/Chirp.CLI.csproj -c Release -r ${{ matrix.os }} --self-contained false -p:PublishSingleFile=true -o ./publish/${{ matrix.os }}
      
    - name: Check working directory and files
      run: |
        pwd
        ls -la ./publish/${{ matrix.os }}
        ls -la

    - name: Create ZIP archive
      run: zip -r Chirp-${{ matrix.os }}.zip ./publish/${{ matrix.os }}

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Chirp-${{ matrix.os }}.zip
        path: Chirp-${{ matrix.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset (Linux)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Chirp-linux-x64.zip
        asset_name: Chirp-linux-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (Windows)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Chirp-win-x64.zip
        asset_name: Chirp-win-x64.zip
        asset_content_type: application/zip

    - name: Upload Release Asset (MacOS)
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Chirp-osx-x64.zip
        asset_name: Chirp-osx-x64.zip
        asset_content_type: application/zip
